### ISSUE TITLE
Perulangan

### ISSUE THREAD

**Issue by DzunN86** [commitunuja/android-kotlin#9]
Membuat materi Perulangan

**Comment by zaiinhs** [comment]
Perulangan ini sudah selesai mas @idlukman ?

**Comment by Lukmanhakim08** [comment]
> Perulangan ini sudah selesai mas @idlukman ?

sdah mas @zaiinhs

**Comment by zaiinhs** [comment]
Diperbaiki yang bagian kata `while, let, this, it` itu mas, bikin gausah bisa di klik atau ada warna biru nya. jadikan text kata biasa aja.

**Comment by Lukmanhakim08** [comment]
Oke siap mas

**Comment by Lukmanhakim08** [comment]
> Diperbaiki yang bagian kata `while, let, this, it` itu mas, bikin gausah bisa di klik atau ada warna biru nya. jadikan text kata biasa aja.

sdah tak ubah mas
